import globals from "globals";
import js from "@eslint/js";

export default [
	{
		"ignores": ["lib/*.js"],
	},
	js.configs.recommended,
	{
		"languageOptions": {
			"globals": {
				...globals.browser,
				"d3": "readonly",
				"sortable": "readonly",
				"mapboxgl": "readonly",
				"GeoTIFF": "readonly",
				"PptxGenJS": "readonly",
				"geojsonExtent": "readonly",
				"SphericalMercator": "readonly",
				"jwt_decode": "readonly",
				"FLASH": "readonly",
				"API": "readonly",
				"SELF": "writable",
				"DST": "readonly",
				"GEOGRAPHY": "writable",
				"SNAPSHOT": "writable",
				"OUTLINE": "writable",
				"MAPBOX": "writable",
				"INFOMODE": "writable",
				"COORDINATES": "writable",
				"COORDINATESMODE": "writable",
				"MOBILE": "writable",
				"EAE": "writable",
				"ENV": "writable",
				"DEBUG": "writable",
				"STATE": "writable",
				"COMMIT": "writable",
				"SUMMARY": "writable",
			},
			"ecmaVersion": "latest",
			"sourceType": "module",
		},
		"rules": {
			"comma-dangle": ["error", "always-multiline"],
			"indent": ["error", "tab"],
			"key-spacing": ["error", {
				"align": {
					"beforeColon": false,
					"afterColon": true,
					"on": "value",
					"mode": "minimum",
				},
			}],
			"linebreak-style": ["error", "unix"],
			"quotes": "off",
			"quote-props": ["error", "always"],
			"semi": ["error", "always"],
			"prefer-const": "error",
			"no-cond-assign": "off",
			"no-console": "off",
			"no-useless-escape": "off",
			"no-extra-semi": "off",
			"no-mixed-spaces-and-tabs": ["error", "smart-tabs"],
			"no-prototype-builtins": "off",
			"no-unused-vars": ["warn", {
				"varsIgnorePattern": "^_",
				"argsIgnorePattern": "^_",
			}],
		},
	},
];
